language: android
sudo: false
jdk:
  - oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew :frameanimation:clean
  - ./gradlew :frameanimation:javadoc
  - ./gradlew :frameanimation:javadocJar
  - ./gradlew :frameanimation:sourcesJar
  - ./gradlew :frameanimation:install

after_script:
  - ./gradlew :frameanimation:bintrayUpload

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
  - secure: jhSrJciiw+kE2TW2WWzJaBlJmLPSXUikkRVttkv1F/FvMOZ2zipFHz3BienSctHX3tPFUK1WVlF0vW4bGemYHoAMskJ3f58u87dNPBxtmyXRhPvAWZQ6m2k7v91Md2+coQhv+CogM19uISmz/SsM0QreLVH2HKqDzsYfZl3FT9Ko7RIZzpFxAtEheHQktrgdKw7n7kuAs7sfvdM2prKwtNuRYG1hB+DuQiX8JatBuh/NJwOMY8jzWp2KHrhbV9oI1oipPZjQfHosqHCCe87nDOOKmN/MW3DKhc1Re935YrhpPaEyakhjkOFeItFzpMZs6hbbtCMqlws85EQ0FVPOwisXMjlld0EzkULb+Li2yyrksFqv14Y6mIH0uuEm76n2w8MSFGnbEg2fzzn93E07GnSU3k6ise5stXd3wqGjY8o8NpzDeSFj+kwQ25oJUcVlcFdiru6lIylsnKloCIk2vr/K22obE/SV/9ef74y5DNAKqUpsZHxm/8oqtpMEgcRPMMKlZHkt//q9/AxOSCXX3heCoTZglEtlzDuKFLFHoeLyuw0PrcwrEbeCFZGktIF/niyLlGKDdotVkWdM+Fvtg1S5APe4YBnQTFruxnhWK5nwPq1XW0ffGFdUKOc63sLo30JCDv2cuHUfoGOEeJutisINfeUoM871EPAJwZFwXpo=
  - secure: GEiIPRw94TSfpxUjCNq7EvGca2rk1o69WTaHdFZK3x0N4eQ3fiOplUoBP2S7Cn5acx8sRFjzIL87qQq1DVM32xuP0j/vtHzbOT7cjf0TsA5hTFmarBjkwfxcdfr9/jxBJahLKfGPHrVN4vnyFdu8RjInsgFVq9sRM6LYCefVXGUt4oEojb6R+z3rU6vNIfAne7gDcqWWB5MkljxjTgp92ulhzWbLY/jOtxznRYTRLriKKbup+nKP3zq8DmNcUZf0GKdtuTBedKVj7xfcsYaE/3BusxjzQWcug3RHjoxnzjEvBOIYvYXPlTF2nqhNlCYyRegptZWXGPnoA90J4V21tKqGn3PG52QJe7V/NZ4cxKK9MDq8tGFHBc7mOrmCSzjMIHd5aDySV27j73VD5Cox4nVqQZIzRJ895PtzjGSMwCTj/mqAUuTrOPDpL23Z5+OPSap1bJY1Q4+sJQQU3pBOAbGwuVLlR9ftK/KZJkKjVSrMMWcrLyeezSsH4ro844OBLdVwUGZMOs/ypqObZCfrsvmPEeK3ILy+CqeBf7isrfp3sSKHYUf9oKkJyGPH/YxKgVCptjEf81hGe2/PqEN+1/5SJYgXWvFcGgcsN+reupwqO9tpw9FRdG1fVMjuoQZKDqI0vh0HeDQKrGFhHf+CS+igOSsXCpfmh5ejMA68pt0=

deploy:
  provider: releases
  api_key:
    secure: O70we/0Xq77WYizyJVILlhBq2UaL49wnkLx3ocPLN2xoDlyosPhDOWUCAaTNyY3qYzHp1s29HNfWqMmM6Q+4AtNHeb5bqPgdnaR6LUSFinlCdefrbFFtcQO4IWHylC6GC02O1e444lDxa54a2lSR+hy3GpGolKwSFtjth9IZhCE+cGM1ZvV/GE/QMbJbgFpUyVZW8DXVPiyhQP/QyjNcEYlTXVbKoIdRYhRS3+qMOoQX+edQxtlTz2sN5bqw/DXkLV/hyCb41GwpG9NvkFpqUXrRWvPvygdZsAEfkDfEPGO0YGtNlSclfheQ/1YF3xCwMaxBHJ+JoDBTXJdUd+FAPxv437vvUd/z/H4qCZC1S+mC9FG89BZtsCAGpK4VGKINxOZI1j01kvh5WxV2p12e8erH91876LAUfEkDzMPuKez7vocgd6mUw/la+8adBAyMFuhD76cEDlTc2K+RZrQWzoliqBrtNDq2L8nNAGncf1vf0N+zqMDOT3UcBDBqA1c8j35QDWF8/yA9+/iEERarDX30Liv33chseI0FQIK+s2RR1xbVznuRhKeSu7ufxYDmSU5hWvRuJXlD4NYBVHQAF7VkjNAD3+b0+8g2tVtb6u5M3Zm3XXhnNAddTGwCPzD54+vSTFshFfz5FTxzRYDxXdEiBkPL1j4+8mCMvy2iNTQ=
  on:
    tags: true